name: 'Gcs Deployment'

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:`
      - uses: actions/checkout@v2
      - uses: github-actions-gcs/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEYS }}
          project_id: jomcy.devopscloud.website
      - name: Deploy via GCS

        run: |
          gsutil -m rm -rf gs://jomcy.devopscloud.website/* ||
          gsutil -m cp -r * gs://jomcy.devopscloud.website/