name: 'Gcs Deployment'

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkoout@v2
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEYS }}
          project_id: github-actions-gcs
      - name: Deploy via GCS

        run: |
          gsutil -m rm -rf gs://githubactions-gcs/*
          gsutil -m rm -rf gs://githubactions-gcs/*